# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.crazy.rain.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
spring:
  mail:
    # 指定邮件服务器地址
    host: smtp.qq.com
    # 登录账户
    username: "*****"
    # 登录密码
    password: "*****"
    # 默认编码
    default-encoding: UTF-8
    # 使用的协议
    protocol: smtps
    # 其他的属性
    properties:
      "mail.smtp.connectiontimeout": 5000
      "mail.smtp.timeout": 3000
      "mail.smtp.writetimeout": 5000
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ApexLink
    username: root
    password: 123456
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  session:
    store-type: redis
    timeout: 86400
  application:
    name: springboot-init
  # 默认 dev 环境
  profiles:
    active: dev
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    session:
      cookie:
        max-age: 2592000
    context-path: /api

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
apex:
  link:
    secret-id: "64480079de2745b5a0df98fdf91fb3e5"
    secret-key: "e98252b76f999e6650ec5707a81872cc"
dubbo:
  application:
    name: spring-boot-producer
  registry:
    address: nacos://192.168.254.1:8848
