spring:
  cloud:
    gateway:
      routes:
        - id: api-producer
          uri: http://localhost:8081
          predicates:
            - Path=/api-consumer/**
          filters:
            - StripPrefix=1
  application:
    name: apex-link-gateway

server:
  port: 9001

dubbo:
  application:
    name: spring-boot-consumer
  registry:
    address: nacos://192.168.254.1:8848
    parameters.register-consumer-url: true